# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-26T12:41:54Z"
  labels:
    app: ncpod
  name: nc_pod
spec:
  containers:
  - args:
    - mariadbd
    env:
    - name: MYSQL_USER
      value: nextcloud
    - name: MYSQL_DATABASE
      value: nc_db
    - name: MYSQL_ROOT_PASSWORD
      value: ToPSeCrEt2021!
    - name: MYSQL_PASSWORD
      value: ToPSeCrEt2021!
    image: docker.io/library/mariadb:10.11.2
    name: ncmariadb
    ports:
    - containerPort: 80
      hostPort: 40671
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql_data-pvc
  - args:
    - apache2-foreground
    env:
    - name: NEXTCLOUD_ADMIN_PASSWORD
      value: VSnfD2021!
    - name: SMTP_AUTHTYPE
      value: LOGIN
    - name: SMTP_NAME
      value: bob@example.com
    - name: NEXTCLOUD_TRUSTED_DOMAINS
      value: 192.168.122.220
    - name: NEXTCLOUD_ADMIN_USER
      value: nc_admin
    - name: MYSQL_DATABASE
      value: nc_db
    - name: SMTP_PORT
      value: "587"
    - name: MYSQL_USER
      value: nextcloud
    - name: MYSQL_HOST
      value: 127.0.0.1
    - name: SMTP_SECURE
      value: tls
    - name: SMTP_PASSWORD
      value: MailSecret1!
    - name: MAIL_FROM_ADDRESS
      value: no-reply
    - name: MAIL_DOMAIN
      value: example.com
    - name: MYSQL_PASSWORD
      value: ToPSeCrEt2021!
    - name: SMTP_HOST
      value: smtp.example.com
    image: docker.io/library/nextcloud:production-apache
    name: nextcloud
    resources: {}
    volumeMounts:
    - mountPath: /var/www/html
      name: nc_html-pvc
    - mountPath: /var/www/html/custom_apps
      name: nc_apps-pvc
    - mountPath: /var/www/html/config
      name: nc_config-pvc
    - mountPath: /var/www/html/data
      name: nc_data-pvc
  hostname: nc_pod
  restartPolicy: Never
  volumes:
  - name: nc_config-pvc
    persistentVolumeClaim:
      claimName: nc_config
  - name: nc_data-pvc
    persistentVolumeClaim:
      claimName: nc_data
  - name: mysql_data-pvc
    persistentVolumeClaim:
      claimName: mysql_data
  - name: nc_html-pvc
    persistentVolumeClaim:
      claimName: nc_html
  - name: nc_apps-pvc
    persistentVolumeClaim:
      claimName: nc_apps
status: {}

