# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: doc/conf.py
  builder: html

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install sphinx==7.1.0 furo==2023.7.26 myst-parser sphinx-design
    - sphinx-build -b html -c doc/ doc/md/ _readthedocs/html/

python:
  install:
    - requirements: doc/requirements.txt
