# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
# Add podman command from which this file was created:
# podman run -d --rm -p 8080:8080 --name apache-demo \
# -v /home/jkastnin/SummitConnectDarmstadt/index.html:/var/www/html/index.html:Z \
# registry.access.redhat.com/ubi9/httpd-24:latest
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /home/jkastnin/SummitConnectDarmstadt/index.html:Z
  creationTimestamp: "2023-10-30T10:56:33Z"
  labels:
    app: apache-demo-pod
  name: apache-demo-pod
spec:
  containers:
  - args:
    - /usr/bin/run-httpd
    image: registry.access.redhat.com/ubi9/httpd-24:latest
    name: apache-demo
    ports:
    - containerPort: 8080
      hostPort: 8080
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /var/www/html/index.html
      name: home-jkastnin-SummitConnectDarmstadt-index.html-host-0
  volumes:
  - hostPath:
      path: /home/jkastnin/SummitConnectDarmstadt/index.html
      type: File
    name: home-jkastnin-SummitConnectDarmstadt-index.html-host-0

