---
- name: Wordpress Demo Playbook
  hosts: localhost
  tasks:
    - name: Deploy Wordpress and MariaDB with Podman Quadlet
      ansible.builtin.include_role:
        name: rhel-system-roles.podman
      vars:
        podman_quadlet_specs:
          - name: wordpress-demo
            type: network
            file_content: |
              [Network]
              Subnet=192.168.30.0/24
              Gateway=192.168.30.1
              Label=app=wordpress
          - file_src: mariadb.volume
          - file_src: wordpress.volume
          - file_src: mariadb.container
            activate_systemd_unit: true
          - file_src: wordpress.container
            activate_systemd_unit: true
        podman_firewall:
          - port: 8080/tcp
            state: enabled
        podman_secrets:
          - name: mysql-root-password-container
            state: present
            data: "{{ mysql_root_password_from_vault }}"
          - name: mysql-user-password-container
            state: present
            data: "{{ mysql_user_password_from_fault }}"
